<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Contact;
use App\Models\Property;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class PropertySeeder extends Seeder
{
    public function run(): void
    {
        $users = User::query()
            ->whereIn('email', ['admin@agence-sahel.sn', 'agent@agence-sahel.sn'])
            ->get()
            ->keyBy('email');

        $categories = Category::query()
            ->whereIn('name', ['Villa', 'Appartement', 'Terrain', 'Maison de vacances', 'Immeuble'])
            ->get()
            ->keyBy('name');

        $contacts = Contact::query()->get()->keyBy('email');

        $properties = [
            [
                'category' => 'Villa',
                'manager_email' => 'admin@agence-sahel.sn',
                'owner_email' => 'mamadou.ndiaye@agence-sahel.sn',
                'tenant_email' => null,
                'title' => 'Magnifique Villa aux Almadies',
                'description' => 'Superbe villa de luxe avec piscine, jardin paysager, grandes terrasses et prestations premium dans un quartier tres recherche.',
                'price' => 250000000,
                'location' => 'Almadies, Dakar',
                'address_line' => 'Route des Almadies',
                'city' => 'Dakar',
                'district' => 'Almadies',
                'latitude' => 14.7429150,
                'longitude' => -17.5212040,
                'type' => 'sale',
                'status' => 'available',
                'area' => 500,
                'rooms' => 5,
                'bathrooms' => 4,
                'parking_spaces' => 3,
                'featured' => true,
                'is_published' => true,
                'seo_title' => 'Villa de luxe aux Almadies avec piscine - Agence Immo Sahel',
                'seo_description' => 'Decouvrez une villa haut standing aux Almadies avec piscine, jardin et finitions premium.',
                'published_at' => now()->subDays(12),
            ],
            [
                'category' => 'Appartement',
                'manager_email' => 'agent@agence-sahel.sn',
                'owner_email' => 'aissatou.ba@agence-sahel.sn',
                'tenant_email' => 'aminata.kane@agence-sahel.sn',
                'title' => 'Appartement F4 avec vue mer',
                'description' => 'Appartement spacieux avec terrasse, belle luminosite et vue degagee sur l\'Atlantique, ideal pour une famille active.',
                'price' => 800000,
                'location' => 'Plateau, Dakar',
                'address_line' => 'Corniche Ouest',
                'city' => 'Dakar',
                'district' => 'Plateau',
                'latitude' => 14.6684700,
                'longitude' => -17.4322100,
                'type' => 'rent',
                'status' => 'rented',
                'area' => 150,
                'rooms' => 4,
                'bathrooms' => 2,
                'parking_spaces' => 1,
                'featured' => false,
                'is_published' => true,
                'seo_title' => 'Appartement F4 avec vue mer au Plateau - Agence Immo Sahel',
                'seo_description' => 'Un appartement familial F4 avec terrasse et vue mer dans un secteur central de Dakar.',
                'published_at' => now()->subDays(9),
            ],
            [
                'category' => 'Villa',
                'manager_email' => 'agent@agence-sahel.sn',
                'owner_email' => 'seydou.fall@agence-sahel.sn',
                'tenant_email' => null,
                'title' => 'Villa Moderne à Ngor',
                'description' => 'Villa contemporaine avec piscine, sejour traversant et belles prestations dans un environnement calme et residentiel.',
                'price' => 200000000,
                'location' => 'Ngor, Dakar',
                'address_line' => 'Rue de Ngor Virage',
                'city' => 'Dakar',
                'district' => 'Ngor',
                'latitude' => 14.7474020,
                'longitude' => -17.5063170,
                'type' => 'sale',
                'status' => 'available',
                'area' => 400,
                'rooms' => 4,
                'bathrooms' => 3,
                'parking_spaces' => 2,
                'featured' => true,
                'is_published' => true,
                'seo_title' => 'Villa moderne a Ngor avec piscine - Agence Immo Sahel',
                'seo_description' => 'Villa contemporaine a Ngor avec piscine et espaces lumineux, ideale pour un achat residence principale.',
                'published_at' => now()->subDays(7),
            ],
            [
                'category' => 'Appartement',
                'manager_email' => 'admin@agence-sahel.sn',
                'owner_email' => 'fatou.diop@agence-sahel.sn',
                'tenant_email' => null,
                'title' => 'Appartement F3 à Mermoz',
                'description' => 'Appartement bien distribue, proche des commerces et des axes principaux, actuellement en phase de remise en etat.',
                'price' => 600000,
                'location' => 'Mermoz, Dakar',
                'address_line' => 'Avenue Cheikh Anta Diop Extension',
                'city' => 'Dakar',
                'district' => 'Mermoz',
                'latitude' => 14.7069840,
                'longitude' => -17.4743230,
                'type' => 'rent',
                'status' => 'maintenance',
                'area' => 100,
                'rooms' => 3,
                'bathrooms' => 1,
                'parking_spaces' => 1,
                'featured' => false,
                'is_published' => true,
                'seo_title' => 'Appartement F3 a Mermoz proche commodites - Agence Immo Sahel',
                'seo_description' => 'Appartement F3 a Mermoz avec bon potentiel locatif, en cours de remise a niveau.',
                'published_at' => now()->subDays(6),
            ],
            [
                'category' => 'Villa',
                'manager_email' => 'admin@agence-sahel.sn',
                'owner_email' => 'khadim.diallo@agence-sahel.sn',
                'tenant_email' => null,
                'title' => 'Villa de Luxe à Fann',
                'description' => 'Villa haut standing avec jardin arbore, piscine et finitions soignees dans l\'un des secteurs les plus apprecies.',
                'price' => 300000000,
                'location' => 'Fann, Dakar',
                'address_line' => 'Rue de Fann Residence',
                'city' => 'Dakar',
                'district' => 'Fann',
                'latitude' => 14.6926500,
                'longitude' => -17.4601200,
                'type' => 'sale',
                'status' => 'available',
                'area' => 600,
                'rooms' => 6,
                'bathrooms' => 5,
                'parking_spaces' => 4,
                'featured' => true,
                'is_published' => true,
                'seo_title' => 'Villa de luxe a Fann avec jardin et piscine - Agence Immo Sahel',
                'seo_description' => 'Bien d\'exception a Fann avec volumes genereux, jardin et prestations haut de gamme.',
                'published_at' => now()->subDays(10),
            ],
            [
                'category' => 'Appartement',
                'manager_email' => 'agent@agence-sahel.sn',
                'owner_email' => 'aissatou.ba@agence-sahel.sn',
                'tenant_email' => 'ousmane.ndao@agence-sahel.sn',
                'title' => 'Appartement F2 à Liberté',
                'description' => 'Appartement cosy de deux pieces, parfait pour un couple ou un jeune actif, dans un secteur pratique et vivant.',
                'price' => 400000,
                'location' => 'Liberté, Dakar',
                'address_line' => 'Liberte 6 Extension',
                'city' => 'Dakar',
                'district' => 'Liberte',
                'latitude' => 14.7202050,
                'longitude' => -17.4543160,
                'type' => 'rent',
                'status' => 'rented',
                'area' => 80,
                'rooms' => 2,
                'bathrooms' => 1,
                'parking_spaces' => 1,
                'featured' => false,
                'is_published' => true,
                'seo_title' => 'Appartement F2 a Liberte - Agence Immo Sahel',
                'seo_description' => 'Appartement F2 pratique a Liberte, adapte a une occupation rapide.',
                'published_at' => now()->subDays(4),
            ],
            [
                'category' => 'Villa',
                'manager_email' => 'admin@agence-sahel.sn',
                'owner_email' => 'khadim.diallo@agence-sahel.sn',
                'tenant_email' => null,
                'title' => 'Villa Contemporaine à Point E',
                'description' => 'Villa moderne avec belle reception, architecture elegante et espaces exterieurs soignes dans un quartier premium.',
                'price' => 350000000,
                'location' => 'Point E, Dakar',
                'address_line' => 'Avenue Cheikh Anta Diop',
                'city' => 'Dakar',
                'district' => 'Point E',
                'latitude' => 14.6972800,
                'longitude' => -17.4668300,
                'type' => 'sale',
                'status' => 'available',
                'area' => 550,
                'rooms' => 5,
                'bathrooms' => 4,
                'parking_spaces' => 3,
                'featured' => true,
                'is_published' => true,
                'seo_title' => 'Villa contemporaine a Point E - Agence Immo Sahel',
                'seo_description' => 'Villa contemporaine au Point E avec reception, piscine et excellentes finitions.',
                'published_at' => now()->subDays(5),
            ],
            [
                'category' => 'Appartement',
                'manager_email' => 'agent@agence-sahel.sn',
                'owner_email' => 'fatou.diop@agence-sahel.sn',
                'tenant_email' => 'mariama.cisse@agence-sahel.sn',
                'title' => 'Appartement F4 à Sacré-Cœur',
                'description' => 'Appartement familial spacieux, bien agence et proche des services essentiels dans le secteur de Sacre-Coeur.',
                'price' => 700000,
                'location' => 'Sacré-Cœur, Dakar',
                'address_line' => 'Sacre-Coeur 3',
                'city' => 'Dakar',
                'district' => 'Sacre-Coeur',
                'latitude' => 14.7235060,
                'longitude' => -17.4631040,
                'type' => 'rent',
                'status' => 'available',
                'area' => 120,
                'rooms' => 4,
                'bathrooms' => 2,
                'parking_spaces' => 1,
                'featured' => false,
                'is_published' => true,
                'seo_title' => 'Appartement F4 a Sacre-Coeur - Agence Immo Sahel',
                'seo_description' => 'Location familiale a Sacre-Coeur avec bonne distribution et acces rapides.',
                'published_at' => now()->subDays(3),
            ],
            [
                'category' => 'Terrain',
                'manager_email' => 'admin@agence-sahel.sn',
                'owner_email' => 'lamine.mbaye@agence-sahel.sn',
                'tenant_email' => null,
                'title' => 'Terrain titré à Saly',
                'description' => 'Terrain bien situe pour projet residentiel ou investissement, dans une zone a fort potentiel de developpement.',
                'price' => 95000000,
                'location' => 'Saly, Mbour',
                'address_line' => 'Route de Saly Niakh Niakhal',
                'city' => 'Mbour',
                'district' => 'Saly',
                'latitude' => 14.4455300,
                'longitude' => -17.0167300,
                'type' => 'sale',
                'status' => 'available',
                'area' => 800,
                'rooms' => null,
                'bathrooms' => null,
                'parking_spaces' => null,
                'featured' => false,
                'is_published' => true,
                'seo_title' => 'Terrain titre a Saly - Agence Immo Sahel',
                'seo_description' => 'Terrain titre a Saly pour residence secondaire ou operation patrimoniale.',
                'published_at' => now()->subDays(8),
            ],
            [
                'category' => 'Maison de vacances',
                'manager_email' => 'agent@agence-sahel.sn',
                'owner_email' => 'seydou.fall@agence-sahel.sn',
                'tenant_email' => null,
                'title' => 'Maison de vacances à Somone',
                'description' => 'Maison chaleureuse avec terrasse et jardin, parfaite pour des sejours en famille ou une location saisonniere.',
                'price' => 120000000,
                'location' => 'Somone, Thiès',
                'address_line' => 'Route de la Lagune',
                'city' => 'Thies',
                'district' => 'Somone',
                'latitude' => 14.4848900,
                'longitude' => -17.0778900,
                'type' => 'sale',
                'status' => 'maintenance',
                'area' => 260,
                'rooms' => 4,
                'bathrooms' => 3,
                'parking_spaces' => 2,
                'featured' => true,
                'is_published' => false,
                'seo_title' => 'Maison de vacances a Somone - Agence Immo Sahel',
                'seo_description' => 'Maison de vacances a Somone avec jardin et terrasse, actuellement en phase de remise en etat.',
                'published_at' => null,
            ],
            [
                'category' => 'Immeuble',
                'manager_email' => 'admin@agence-sahel.sn',
                'owner_email' => 'bocar.sy@agence-sahel.sn',
                'tenant_email' => null,
                'title' => 'Immeuble de rapport à Rufisque',
                'description' => 'Immeuble avec plusieurs niveaux et bon potentiel locatif, ideal pour un investisseur a la recherche de rendement.',
                'price' => 450000000,
                'location' => 'Rufisque, Dakar',
                'address_line' => 'Boulevard Maurice Gueye',
                'city' => 'Dakar',
                'district' => 'Rufisque',
                'latitude' => 14.7176500,
                'longitude' => -17.2734100,
                'type' => 'sale',
                'status' => 'available',
                'area' => 900,
                'rooms' => 12,
                'bathrooms' => 8,
                'parking_spaces' => 6,
                'featured' => true,
                'is_published' => true,
                'seo_title' => 'Immeuble de rapport a Rufisque - Agence Immo Sahel',
                'seo_description' => 'Actif de rendement a Rufisque avec plusieurs lots et bon potentiel d\'exploitation.',
                'published_at' => now()->subDays(11),
            ],
        ];

        foreach ($properties as $propertyData) {
            $category = $categories->get($propertyData['category']);
            $manager = $users->get($propertyData['manager_email']) ?? $users->first();
            $owner = $contacts->get($propertyData['owner_email']);
            $tenant = $propertyData['tenant_email'] ? $contacts->get($propertyData['tenant_email']) : null;

            if (! $category || ! $manager) {
                continue;
            }

            $title = $propertyData['title'];
            $slug = Str::slug($title);

            Property::query()->updateOrCreate(
                ['slug' => $slug],
                [
                    'category_id' => $category->id,
                    'user_id' => $manager->id,
                    'owner_contact_id' => $owner?->id,
                    'tenant_contact_id' => $tenant?->id,
                    'title' => $title,
                    'description' => $propertyData['description'],
                    'price' => $propertyData['price'],
                    'location' => $propertyData['location'],
                    'address_line' => $propertyData['address_line'],
                    'city' => $propertyData['city'],
                    'district' => $propertyData['district'],
                    'latitude' => $propertyData['latitude'],
                    'longitude' => $propertyData['longitude'],
                    'type' => $propertyData['type'],
                    'status' => $propertyData['status'],
                    'area' => $propertyData['area'],
                    'rooms' => $propertyData['rooms'],
                    'bathrooms' => $propertyData['bathrooms'],
                    'parking_spaces' => $propertyData['parking_spaces'],
                    'featured' => $propertyData['featured'],
                    'is_published' => $propertyData['is_published'],
                    'seo_title' => $propertyData['seo_title'],
                    'seo_description' => $propertyData['seo_description'],
                    'published_at' => $propertyData['published_at'],
                ],
            );
        }
    }
}
